### ISSUE TITLE
🐛  Error when Running `poetry install`

### ISSUE THREAD

**Issue by ARYAN-NIKNEZHAD** [sageteamorg/python-sage-imap#15]
I encountered an error while trying to install packages using **Poetry** with the command:
   ```bash
   poetry install
   ```
   The error message is as follows:
> Current **Python** version (3.11) is not allowed

**Comment by ARYAN-NIKNEZHAD** [comment]
🎉 Solution Implemented! 🎉

I’ve identified a solution to address the issue and have submitted a pull request with the necessary changes. Once the pull request is reviewed and merged, this issue should be resolved. Please feel free to close this issue if the changes meet the requirements.

Thank you for your attention! 🙌

**Comment by sepehr-akbarzadeh** [comment]
I will review it.

Thanks for your contribution
