### ISSUE TITLE
Missing `UID` Method in `IMAPSearchCriteria` Class

### ISSUE THREAD

**Issue by radinceorc** [sageteamorg/python-sage-imap#18]
#### Description:
The `IMAPSearchCriteria` class currently does not have a `UID` method. This method needs to be added to provide unique identification functionality.

#### Steps to Reproduce:
1. Attempt to call the `UID` method on an instance of the `IMAPSearchCriteria` class.
2. Observe that the method does not exist.

Link to the exact class: [IMAPSearchCriteria](https://github.com/sageteamorg/python-sage-imap/blob/d84fbf342bca0ec483e3a9ee6502dee1b04ce4ff/sage_imap/helpers/search.py#L5C7-L5C25)

**Comment by ARYAN-NIKNEZHAD** [comment]
Hi @radinceorc,

Thank you for identifying the lack of a UID method in the IMAPSearchCriteria class. We have now added the uid method to generate search criteria based on unique identifiers (UIDs).

Here’s an example of how to use the new method:

```python

criteria = IMAPSearchCriteria.uid("100")
print(criteria)  # Output: UID 100

criteria = IMAPSearchCriteria.uid("100:200")
print(criteria)  # Output: UID 100:200
```

Please feel free to modify it as needed to better suit your requirements✨.
