### ISSUE TITLE
Add Feature: Upload .eml Files to IMAP Server

### ISSUE THREAD

**Issue by MohmdFo** [sageteamorg/python-sage-imap#3]
I would like to request a new feature that allows users to upload .eml files directly to an IMAP server.

**Use Case:**
This feature would be highly beneficial for users who need to import archived emails or migrate emails from one server to another. By supporting .eml file uploads, users can easily manage and organize their email data within the IMAP server without the need for complex workarounds.

**Proposed Solution:**
- Implement functionality to select and upload .eml files via the web interface or an API endpoint.
- Ensure the uploaded .eml files are correctly parsed and stored in the appropriate folders on the IMAP server.
- Provide feedback to the user regarding the success or failure of the upload process.

**Comment by sepehr-akbarzadeh** [comment]
Hi @MohmdFo,

Welcome and thank you for the issue! To contribute:

1. **Fork & Clone**: Fork the repo and clone it locally.
2. **Git Flow**: Install and init Git Flow.
3. **Feature Branch**: `git flow feature start upload-eml-files`
4. **Commit**: Use Commitizen for commits.
5. **Finish Branch**: `git flow feature finish upload-eml-files`
6. **Push & PR**: Push to GitHub and create a pull request, referencing this issue.

We appreciate your contribution!
