### ISSUE TITLE
Make Mailbox Folder Names Configurable Instead of Hardcoded

### ISSUE THREAD

**Issue by MohmdFo** [sageteamorg/python-sage-imap#4]
The current implementation hardcodes the mailbox folder names, which causes compatibility issues with different IMAP servers where folder names might vary.

**Relevant Code:**
The specific part of the code where the mailbox folders are hardcoded can be found here: [mailbox.py line 4](https://github.com/sageteamorg/python-sage-imap/blob/91ee95cec72685d82fd739a07c179d606466c09b/sage_imap/helpers/mailbox.py#L4)

**Proposed Solution:**
- Modify the code to allow users to configure and select mailbox folder names rather than relying on hardcoded values.
- Implement a configuration file or settings parameter where users can define their mailbox folder names according to their specific IMAP server requirements.

**Comment by sepehr-akbarzadeh** [comment]
Now this issue fixed.
